name: Keep Backend Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend Health Endpoint
        run: curl -sSf https://rts-backend-8b7d.onrender.com/actuator/health || echo "Failed but workflow will not crash"
